/**
 * Local hero names list
 * This is used instead of fetching from API for better performance
 * Hero URLs are fetched dynamically when voice lines are loaded for each hero
 */
export const HERO_NAMES = [
  'Abaddon',
  'Alchemist',
  'Ancient Apparition',
  'Anti-Mage',
  'Arc Warden',
  'Axe',
  'Bane',
  'Batrider',
  'Beastmaster',
  'Bloodseeker',
  'Bounty Hunter',
  'Brewmaster',
  'Bristleback',
  'Broodmother',
  'Centaur Warrunner',
  'Chaos Knight',
  'Chen',
  'Clinkz',
  'Clockwerk',
  'Crystal Maiden',
  'Dark Seer',
  'Dark Willow',
  'Dawnbreaker',
  'Dazzle',
  'Death Prophet',
  'Disruptor',
  'Doom',
  'Dragon Knight',
  'Drow Ranger',
  'Earth Spirit',
  'Earthshaker',
  'Elder Titan',
  'Ember Spirit',
  'Enchantress',
  'Enigma',
  'Faceless Void',
  'Grimstroke',
  'Gyrocopter',
  'Hoodwink',
  'Huskar',
  'Invoker',
  'Io',
  'Jakiro',
  'Juggernaut',
  'Keeper of the Light',
  'Kunkka',
  'Legion Commander',
  'Leshrac',
  'Lich',
  'Lifestealer',
  'Lina',
  'Lion',
  'Lone Druid',
  'Luna',
  'Lycan',
  'Magnus',
  'Marci',
  'Mars',
  'Medusa',
  'Meepo',
  'Mirana',
  'Monkey King',
  'Morphling',
  'Muerta',
  'Naga Siren',
  'Nature\'s Prophet',
  'Necrophos',
  'Night Stalker',
  'Nyx Assassin',
  'Ogre Magi',
  'Omniknight',
  'Oracle',
  'Outworld Destroyer',
  'Pangolier',
  'Phantom Assassin',
  'Phantom Lancer',
  'Phoenix',
  'Primal Beast',
  'Puck',
  'Pudge',
  'Pugna',
  'Queen of Pain',
  'Razor',
  'Riki',
  'Rubick',
  'Sand King',
  'Shadow Demon',
  'Shadow Fiend',
  'Shadow Shaman',
  'Silencer',
  'Skywrath Mage',
  'Slardar',
  'Slark',
  'Snapfire',
  'Sniper',
  'Spectre',
  'Spirit Breaker',
  'Storm Spirit',
  'Sven',
  'Techies',
  'Templar Assassin',
  'Terrorblade',
  'Tidehunter',
  'Timbersaw',
  'Tinker',
  'Tiny',
  'Treant Protector',
  'Troll Warlord',
  'Tusk',
  'Underlord',
  'Undying',
  'Ursa',
  'Vengeful Spirit',
  'Venomancer',
  'Viper',
  'Visage',
  'Void Spirit',
  'Warlock',
  'Weaver',
  'Windranger',
  'Winter Wyvern',
  'Witch Doctor',
  'Wraith King',
  'Zeus',
].sort();

export interface HeroInfo {
  hero: string;
  url: string;
}

/**
 * Get hero list as HeroInfo array
 * URLs are empty by default and will be populated when voice lines are fetched
 */
export function getHeroes(): HeroInfo[] {
  return HERO_NAMES.map(hero => ({
    hero,
    url: '', // URL will be set when voice lines are fetched for this hero
  }));
}

